basically working fleetsie_gen + fleetsie_gen_server
- TODO: need forced command on keys in
 /home/fleetsie_FLEET/.ssh/authorized_keys

diff --git a/fleetsie_srv b/fleetsie_srv
--- a/fleetsie_srv
+++ b/fleetsie_srv
@@ -27,19 +27,31 @@ if ! ssh $SSHUSER date > /dev/null 2>/tmp/error.txt; then
 fi
 
 echo Confirmed that $SSHUSER is valid.
-if [[ ! sqlite3 -version ]]; then
-    echo Installing missing packages...
-    ssh $SSHUSER sudo apt-get update
-    ssh $SSHUSER sudo apt install sqlite3
-fi
-echo Creating user fleetsie - you will need to enter a new password twice...
-ssh $SSHUSER sudo adduser  --gecos '""' fleetsie
-ssh $SSHUSER sudo usermod -a -G sudo fleetsie
-echo Generating ssh keys for user fleetsie
-TARGFILE=~/.ssh/id_ed25519_fleetsie_$SERVER
-ssh-keygen -P "" -t ed25519 -f $TARGFILE
-echo Adding config to ~/.ssh for fleetsie@$SERVER
-cat >> ~/.ssh/config <<EOF
+printf "Ensuring required packages are installed...\n"
+PACKAGES="sqlite3 rsync"
+for p in $PACKAGES; do
+    if ! ssh $SSHUSER dpkg -l $p > /dev/null 2>&1; then
+	# just install all so we only call update once
+	echo Installing missing packages including $p ...
+	ssh $SSHUSER sudo apt-get update
+	ssh $SSHUSER sudo apt install -y sqlite3 rsync
+	break
+    fi
+done
+FLEETSIE_SSHUSER=fleetsie@$SERVER
+if ! ssh $FLEETSIE_SSHUSER date > /dev/null 2>&1; then
+    echo Creating user fleetsie - you will need to enter a new password twice...
+    ssh $SSHUSER sudo adduser  --gecos '""' fleetsie
+    ssh $SSHUSER sudo usermod -a -G sudo fleetsie
+    TARGFILE=~/.ssh/id_ed25519_fleetsie_$SERVER
+    if [[ ! -f $TARGFILE ]]; then
+	echo Generating ssh keys for user fleetsie
+	ssh-keygen -P "" -t ed25519 -f $TARGFILE
+	FLEETSIE_COMMENT='# added by fleetsie_srv'
+	if ! grep "$FLEETSIE_COMMENT" ~/.ssh/config >/dev/null; then
+	    echo Adding config to ~/.ssh for fleetsie@$SERVER
+	    cat >> ~/.ssh/config <<EOF
+# added by fleetsie_srv
 Host $SERVER
   Hostname $SERVER
   User fleetsie
@@ -47,12 +59,16 @@ Host $SERVER
   IdentityFile $TARGFILE
   IdentitiesOnly true
 EOF
-echo Adding new key to authorized_keys file for fleetsie@$SERVER
-ssh $SSHUSER sudo mkdir /home/fleetsie/.ssh
-cat ${TARGFILE}.pub | ssh $SSHUSER sudo tee /home/fleetsie/.ssh/authorized_keys
-echo Changing ownership of .ssh directory for fleetsie@$SERVER
-ssh $SSHUSER sudo chown -R fleetsie:fleetsie /home/fleetsie/.ssh/
-echo Uploading fleetsie_login and fleetsie_auth programs to fleetsie@$SERVER
-scp ./fleetsie_login ./fleetsie_auth ./fleetsie_gen_server fleetsie@$SERVER:
-ssh fleetsie@$SERVER chmod g-w fleetsie_login fleetsie_auth fleetsie_gen_server
+	fi
+    fi
+    echo Adding new key to authorized_keys file for $FLEETSIE_SSHUSER
+    ssh $SSHUSER sudo mkdir -p /home/fleetsie/.ssh
+    cat ${TARGFILE}.pub | ssh $SSHUSER sudo tee /home/fleetsie/.ssh/authorized_keys > /dev/null
+    echo Changing ownership of .ssh directory for $FLEETSIE_SSHUSER
+    ssh $SSHUSER sudo chown -R fleetsie:fleetsie /home/fleetsie/.ssh/
+fi
+echo Updating fleetsie_login, fleetsie_auth, fleetsie_gen_server programs at $FLEETSIE_SSHUSER
+for f in fleetsie_login fleetsie_auth fleetsie_gen_server; do
+    rsync -av ./$f $FLEETSIE_SSHUSER:$f
+done
 exit 0
