further database copy refinement

diff --git a/fleetsie_gen b/fleetsie_gen
--- a/fleetsie_gen
+++ b/fleetsie_gen
@@ -43,7 +43,8 @@ where
    called "fleetsie" as the destination for installing files, rather
    than a disk partition. This can be used for testing.
 
-
+   If both NUM and USB_PARTITION are missing, fleetsie_gen verifies
+   that it can ssh as fleetsie@FLEET_HOST, then exits.
 
 fleetsie_gen creates files on a USB drive and on the fleet server such
 that a number of devices can be provisioned (using the USB drive) with
@@ -91,6 +92,64 @@ EOF
     exit 1
 }
 
+function die () {
+    printf "$*\n"
+    exit 1
+}
+
+function die_with_usage () {
+    printf "$*\n"
+    usage
+}
+
+# get_arg saves $1 into the named parameter,
+# or dies with an error message.
+function get_arg () {
+    declare -n v=$1
+    if [[ ! "$1" ]]; then
+	die_with_usage missing parameter $1
+    fi
+    $v=$1
+    shift
+}
+
+get_arg FLEET_NAME
+get_arg FLEET_HOST
+if ! ssh -v fleetsie@$FLEET_HOST date 2>/tmp/errmsg.txt 1>&2; then
+    die "unable to ssh to fleetsie@$FLEET_HOST: " "`cat /tmp/errmsg.txt`"
+fi
+
+if [[ ! "$1" ]]; then
+    printf "ssh to fleetsie@$FLEET_HOST succeeded\n" >&2
+    exit 0
+fi
+if [[ "$1" =~ ^[0-9]+$ ]]; then
+    NUM=$1
+    shift
+fi
+USB_PARTITION=$1
+
+# if NUM > 0, we generate N new devices for the fleet.  This is done by running
+# a script on the server, then fetching the client version of the table for the fleet
+if [[ $NUM -gt 0 ]]; then
+    printf "Adding $NUM devices to fleet $FLEET_NAME\n"
+    ssh fleetsie@$FLEET_HOST ./fleetsie_gen_server $FLEET_NAME $NUM
+    scp fleetsie@$FLEET_HOST /home/fleetsie_$FLEET_NAME/provisioning
+
+
+## separate host side from client side
+coproc SQL { sqlite3 -column $CONFIG_DB 2>&1; }
+FROMSQL=${SQL[0]}
+TOSQL=${SQL[1]}
+sleep 0.1
+printf ".prompt \"\" \"\"\n" >&$TOSQL
+printf ".timeout 1000\n" >&$TOSQL
+read -t 0.1 ignore <&$FROMSQL
+read -t 0.1 ignore <&$FROMSQL
+# do_cmd runs a command in the attached sqlite database
+do_cmd() {
+    printf "%s;\n" "$1" >&$TOSQL
+}
 
 # notes on what the db looks like
 # create table devices (
